/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Jugador.Jugadores;
import WindowsListener.IrAlMenu;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author baquiax
 */
public class MostrarJugadores extends javax.swing.JFrame {
    
    VentanaPrincipal menu;
    Jugadores jugadores;

    /**
     * Creates new form MostrarJugadores
     *
     * @param menu
     * @param jugadores
     */
    public MostrarJugadores(VentanaPrincipal menu, Jugadores jugadores) {
        this.menu = menu;
        this.jugadores = jugadores;
        initComponents();
        iniciarTablero();
        
        IrAlMenu irAlMenu = new IrAlMenu(menu, this);
        super.addWindowListener(irAlMenu);
        super.setResizable(false);
        super.setLocationRelativeTo(null);
        super.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTituloJugadores = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTablaJugadores = new javax.swing.JTable();
        btnOrdenarPG = new javax.swing.JButton();
        btnOrdenarPJ = new javax.swing.JButton();
        btnOrdenarPP = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Jugadores");

        lblTituloJugadores.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        lblTituloJugadores.setText("Jugadores");

        tblTablaJugadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTablaJugadores);

        btnOrdenarPG.setText("Ordenar PG");
        btnOrdenarPG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarPGActionPerformed(evt);
            }
        });

        btnOrdenarPJ.setText("Ordenar PJ");
        btnOrdenarPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarPJActionPerformed(evt);
            }
        });

        btnOrdenarPP.setText("Ordenar PP");
        btnOrdenarPP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrdenarPPActionPerformed(evt);
            }
        });

        jLabel1.setText("*PJ - Partidas Jugadas          *PG - Partidas Ganadas          *PP - Paridas Perdidas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTituloJugadores)
                .addGap(237, 237, 237))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(btnOrdenarPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnOrdenarPG, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnOrdenarPP, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(0, 81, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTituloJugadores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOrdenarPJ)
                    .addComponent(btnOrdenarPG)
                    .addComponent(btnOrdenarPP))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOrdenarPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarPJActionPerformed
        // TODO add your handling code here:
        jugadores.ordenarJugadoresPorPJ();
        iniciarTablero();
    }//GEN-LAST:event_btnOrdenarPJActionPerformed

    private void btnOrdenarPGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarPGActionPerformed
        // TODO add your handling code here:
        jugadores.ordenarJugadoresPorPG();
        iniciarTablero();
    }//GEN-LAST:event_btnOrdenarPGActionPerformed

    private void btnOrdenarPPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrdenarPPActionPerformed
        // TODO add your handling code here:
        jugadores.ordenarJugadoresPorPP();
        iniciarTablero();
    }//GEN-LAST:event_btnOrdenarPPActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOrdenarPG;
    private javax.swing.JButton btnOrdenarPJ;
    private javax.swing.JButton btnOrdenarPP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTituloJugadores;
    private javax.swing.JTable tblTablaJugadores;
    // End of variables declaration//GEN-END:variables

    private void iniciarTablero() {
        tblTablaJugadores.setModel(new DefaultTableModel(jugadores.listarDatosJtable(), jugadores.listarTituloJTable()));
    }
}
